# Generated by Django 4.1.2 on 2022-11-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NccsPurpose',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'nccs purpose',
                'verbose_name_plural': 'nccs purposes',
                'db_table': 'non_profits_nccs_purpose',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
