# Generated by Django 4.1.2 on 2022-11-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nccs_type', '0001_initial'),
        ('nccs_category', '0001_initial'),
        ('organization', '0002_alter_organization_options'),
        ('nccs_sub_group', '0001_initial'),
        ('nccs_purpose', '0001_initial'),
        ('nccs_class', '0001_initial'),
        ('nccs_major_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.organization')),
                ('class', models.CharField(default=None, max_length=256, null=True)),
                ('sub_group', models.CharField(default=None, max_length=256, null=True)),
                ('purpose', models.CharField(default=None, max_length=256, null=True)),
                ('major_group', models.CharField(default=None, max_length=256, null=True)),
                ('category', models.CharField(default=None, max_length=256, null=True)),
                ('ein', models.CharField(default=None, max_length=256, null=True)),
                ('public_private', models.CharField(default=None, max_length=256, null=True)),
                ('nccs_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_category.nccscategory')),
                ('nccs_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_class.nccsclass')),
                ('nccs_major_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_major_group.nccsmajorgroup')),
                ('nccs_purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_purpose.nccspurpose')),
                ('nccs_sub_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_sub_group.nccssubgroup')),
                ('nccs_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='nccs_type.nccstype')),
            ],
            options={
                'verbose_name': 'non profit',
                'verbose_name_plural': 'non profits',
                'db_table': 'non_profits_non_profit',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('organization.organization', models.Model),
        ),
    ]
