# Generated by Django 4.1.2 on 2022-11-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.organization')),
                ('purpose', models.CharField(default=None, max_length=256, null=True)),
                ('ein', models.CharField(default=None, max_length=256, null=True)),
                ('class', models.CharField(default=None, max_length=256, null=True)),
                ('category', models.CharField(default=None, max_length=256, null=True)),
                ('major_group', models.CharField(default=None, max_length=256, null=True)),
                ('public_private', models.CharField(default=None, max_length=256, null=True)),
                ('sub_group', models.CharField(default=None, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'non profit',
                'verbose_name_plural': 'non profits',
                'db_table': 'non_profits_non_profit',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('organization.organization',),
        ),
    ]
