# Generated by Django 4.1.2 on 2022-11-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='class',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='major_group',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='public_private',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='sub_group',
        ),
    ]
