_base_model: &base_model
    admin_roles: [ non-profit-admin ]
    view_roles: [ non-profit-auditor ]

roles:
    non-profit-admin: Non-profit administrator (full privileges over all non-profits)
    non-profit-auditor: Non-profit auditor (viewing privileges over all non-profits)

models:
    nccs_type:
        <<: *base_model
        base: name_resource
        display: "<name> (<label>)"
        priority: 70
        fields:
            label:
                type: string

    nccs_class:
        <<: *base_model
        base: name_resource
        display: "<name> (<label>)"
        priority: 70
        fields:
            label:
                type: string

    nccs_category:
        <<: *base_model
        base: name_resource
        display: "<name> (<label>)"
        priority: 70
        fields:
            label:
                type: string

    nccs_major_group:
        <<: *base_model
        base: name_resource
        display: "<name> (<label>)"
        priority: 70
        fields:
            label:
                type: string

    nccs_sub_group:
        <<: *base_model
        base: name_resource
        display: "<name> (<label>)"
        priority: 70
        fields:
            label:
                type: string

    nccs_purpose:
        <<: *base_model
        base: name_resource
        display: "<name> (<text>)"
        priority: 70
        fields:
            text:
                type: text

    non_profit:
        <<: *base_model
        base: organization
        extend: true
        mixins:
            - nccs_type
            - nccs_class
            - nccs_category
            - nccs_major_group
            - nccs_sub_group
            - nccs_purpose
        display: "<name>"
        priority: 70
        fields:
            ein:
                type: string
