_base_model: &base_model
    admin_roles: [ non-profit-admin ]
    view_roles: [ non-profit-auditor ]

roles:
    non-profit-admin: Non-profit administrator (full privileges over all non-profits)
    non-profit-auditor: Non-profit auditor (viewing privileges over all non-profits)

models:
    non_profit:
        <<: *base_model
        base: organization
        extend: true
        display: "<name>"
        priority: 70
        fields:
            ein:
                type: string
            class:
                type: string
            public_private:
                type: string
            category:
                type: string
            major_group:
                type: string
            sub_group:
                type: string
            purpose:
                type: string
